### ISSUE TITLE
use a sagemaker notebook with GPUs

### ISSUE THREAD

**Issue by psteinb** [hzdr/d3hack2019-docs#1]
AWS staff has advised me to *NOT* create notebooks using ml.p2.xlarge instances, which in turn would bring along GPU nodes. They said, this is way too expensive.

Checking the pricing: https://aws.amazon.com/ec2/pricing/on-demand/ for EU (Frankfurt), I see that these instances cost `$1.326 per Hour`. Instead they suggested to use
- ml.c5.xlarge (4 vCPU, 8GB RAM) at `$0.194 per Hour`
- ml.m5.4xlarge (4 vCPU, 16GB RAM) at `$0.23 per Hour`

The AWS engineer mentioned that calls to training methods can be sent to `ml.p2.xlarge` per function invocation. This has to be researched & documented.

**Comment by oliverguhr** [comment]
Here is a nice description of how Amazon designed the [sagemaker workflow](https://aws.amazon.com/de/getting-started/tutorials/build-train-deploy-machine-learning-model-sagemaker/)
Basically, you run your notebook on a cheap instance and use it to prepare your data. Then you move your cleaned data to s3 and invoke the training process on a beefier instance.

I am not sure if this workflow fits all teams. Especially if a team would like to define and debug custom architectures.

**Comment by psteinb** [comment]
And tons of boilerplate code is required to run the model. To my surprise, the HPC cluster inward planning to use has come up with a decent interface to spawn notebooks on their powe9 nodes. I’ll document that tomorrow.

**Comment by oliverguhr** [comment]
IMHO Amazon's workflow might be great if you want to build some kind of CI/CD pipeline for your models. 
In our case, I would build and test my model on a local pc with a small subset of the data and move everything to VM for the final training.
